### ISSUE TITLE
Fix tests for parameters in the OpenAPI document in case of compact API

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wfs30#40]
The tests limitParameter, boundingBoxParameter and timeParameter in GetFeaturesOperation fails if the api definition has a compact API (http://cloudsdi.geo-solutions.it/geoserver/wfs3/).

**Comment by lgoltz** [comment]
A new data provider was added to get all paths for /collection/{id}/items paths from api definition: 
https://github.com/opengeospatial/ets-wfs30/commit/5f32b86405484efeeb38ede0b875465edb57f897

Not tested against http://cloudsdi.geo-solutions.it/geoserver/wfs3/

**Comment by aaime** [comment]
Still failing, the issue is here:

https://github.com/opengeospatial/ets-wfs30/blob/e9e4bbe317c1d110eeaf9ab0e822ccbb5032c695/src/main/java/org/opengis/cite/wfs30/collections/GetFeaturesOperation.java#L476

and in particular in the findParameterByName call, it's looking for a "/collections/sf__PrimitiveGeoFeature/items" which is not in the API because of its compact nature, it should be looking for a "/collections/{collectionId}/items" with a specification that collectionId can be "sf__PrimitiGeoFeature" instead

**Comment by aaime** [comment]
Same happens for the checks on limit and time in the same class.

**Comment by lgoltz** [comment]
@aaime The fix is not merged yet, because we could not test against your service (one of http://cloudsdi.geo-solutions.it/geoserver/wfs3, http://cloudsdi.geo-solutions.it/geoserver/daraa/wfs3, http://cloudsdi.geo-solutions.it/geoserver/zaatari/wfs3). They are currently not running, can you take a look at them?

**Comment by aaime** [comment]
Eh, I've noticed, the server deploys off the nightly builds and we just switched from version 2.14 to version 2.15, which caused all non core extensions to disappear from the server. Unfortunately I could not fix it yet and the devops in charge of it is in vacation.
Could you make a pull request with the changes? I could run local tests from it.

**Comment by lgoltz** [comment]
@aaime Merged! Thanks for testing it!
