### ISSUE TITLE
Exhaustive paging tests unecessary slow/too many requests performed

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ets-wfs30#43]
The paging tests seem to page through the whole collection in pages of 6 items. For a layer like Zaatari's StructurePnt, holding over 2000 features, that's a lot of requests and a lot of checks.
I believe these checks should be given some limit. Suggestion:

- Do a first request and check the numberMatched
- Restart, with a page size that makes sure not too many requests are done against that collection (I'd limit it to 10 requests)
- If that would require to load too many features in one shot, or it's going beyond the max limit value, just do two requests, the first page, and the second page, and be done with it

The idea would be to avoid having to do too many round trips, but limit them to a reasonable amount of requests per collection, since each round trip is expensive.

**Comment by aaime** [comment]
As we discussed in the call, also doing the polar tests with relatively large bounding boxes might be problematic in terms of runtime, the dataset could contain a lot of features in that area (millions or more).
It's not an issue of making the bbox smaller, I believe one has to limit it using the limit parameter to ensure no more than N features are returned. 
Mind, it's an improvement, but one could still have a small number of features with a very large number of coordinates (e..g, the GSHHG dataset at http://www.soest.hawaii.edu/wessel/gshhg/ )

**Comment by lgoltz** [comment]
@aaime Thank you for reporting! It is correct, that the number ob request strongly depends from the number of collections and features the service provides. This may lead to serious problems on the server side as well as in the test suite. 

One reason is test method 6 described in the ATS  [A.4.4.10. Validate the Get Features Operation Response](https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#_validate_the_get_features_operation_response) testing the property `numberMatched` (I assume this are the test you named 'paging test'): 
```
If a property numberMatched is included in the response, iteratively follow the next links 
until no next link is included and count the aggregated number of features returned in all 
responses during the iteration. Validate that the value is identical to the numberReturned 
stated in the initial response.
``` 
As A.4.4.10 is referenced in several other tests (in braces the number of test currently implemented):
 * A.4.4.9. Validate the Get Features Operation (1)
 * A.4.4.11. Limit Parameter (2 per collection) 
 * A.4.4.12. Bounding Box Parameter (6 per collection)
 * A.4.4.13. Time Parameter (3 per collection)

I propose the following tasks to reduce the number of requests:
1. Limit the number of collections tested by the ets
   * We should allow the user to  specify the number of collections (or all collections) tested by the ets
   * Default could be 2 (or 5 or 10?)
1. Execute test method 6 of A.4.4.10 only for test A.4.4.9. Validate the Get Features Operation
   * Use a value as hight as possible (limit -> maximum)
1.  Replace the randomly selected limits used in test `limitParameter_requests` by two values derived from the description of the limit parameter, e.g:
    *  if min = max => use this value
    * else =>  use min and min + ((max -min) / 2)
    * if 2. is implemented only one request per limit and collection is send

**Comment by cmheazel** [comment]
@lgoltz @aaime  I like the idea of allowing the tester to set limits.  There may be other places where limits are needed so let's think in terms of a general solution.  In addition, there must be a minimum value so that a tester cannot shortcut a test by setting trivial value.  

I suggest that the limit work something like this:
1) If the test fails or completely succeeds, do not report on the limit.
2) If the test succeeds but was truncated due to the limit.  Report this fact as well as the relevant metrics in the report.  This is not a failure, but it is not a clean pass either.  A Warning perhaps?  
3) Develop a CITE policy on how we are handling test results which include a Warning.  This mainly has to do with the OGC stamp of approval.

If we do this, then I don't think we need to restrict A.4.4.11, 12, or 13.

I endorse #3.  Tests should be repeatable and I don't know why I wrote the ATS this way (I know better).

**Comment by cmheazel** [comment]
I'm thinking of adding a requirement to WFS 3.0 - "WFS 3.0 implementations shall comply with the principle of least astonishment."  The purpose of this requirement is to provide criteria for judging the "quality" of an implementation.  For example, a WFS which returns thousands of features but does not support paging.  Failing this requirement generates a warning (as above) rather than a fail.

Thoughts?

**Comment by cmheazel** [comment]
Consensus:
1.a) Allow the user to limit the number of collections and Features.  Modify ATS to allows.
1.b) Set a default value for the number of collections/Features limit.  This is overridden by a user specified value.
2) Leave ATS as is.  
3) Use the approach described above to provide repeatable test parameters. Modify ATS.

**Comment by lgoltz** [comment]
Tasks described in https://github.com/opengeospatial/ets-wfs30/issues/43#issuecomment-422290174 was implemented: PR #44

**Comment by dstenger** [comment]
Test suite is much fast now as not all collections are considered any more.
The GUI was also enhanced to configure considered collections dynamically.

@aaime Can you please test this enhancement and close this issue if you confirm that the performance problem is solved?

**Comment by dstenger** [comment]
Tested successfully as stated during Testbed 14 meeting.
