### ISSUE TITLE
A.4.4.15 skipped test - 'Could not find a response'

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ets-wfs30#63]
Hi: I am getting a skipped test per below? What are the tests looking for so as NOT to skip?

validate The Get Feature Operation Response | Implements A.4.4.15. Validate the Get Feature Operation Response (Requirement 32) \|                    Details ↗ | 03:39:48 | 0 ms | Could not find a response for collection with name ne_110m_populated_places_simple
-- | -- | -- | -- | --

**Comment by lgoltz** [comment]
@tomkralidis Can you provide the URL of the service?
Please check if the test `getFeatureOperation` for the collection with the same name (ne_110m_populated_places_simple) was successful. The test `validateTheGetFeatureOperationResponse` validates the response of `getFeatureOperation`, so this test must be successful, otherwise the response is not available and the test `validateTheGetFeatureOperationResponse` is skipped.

**Comment by lgoltz** [comment]
`getFeatureOperation` is not successfull, as documented in #62

**Comment by tomkralidis** [comment]
@lgoltz http://ec2-18-222-159-167.us-east-2.compute.amazonaws.com/pygeoapi/

Can I find, within each test name, the actual request being run so as to isolate and debug?

**Comment by lgoltz** [comment]
Usually the request is available if the test fails. Tests are skipped cause of not fulfilled preconditions, mostly failing tests. In the old report the dependencies betweens tests can be followed by the property "Depends on methods" (and "Depends on groups" if the assignment to a group would be document) in the details of a test.

**Comment by dstenger** [comment]
@tomkralidis 
When testing service of https://github.com/opengeospatial/ets-wfs30/issues/62#issuecomment-504077701 with test suite containing fix for #62, the test is passing.
If you can confirm this, please close the issue.

**Comment by tomkralidis** [comment]
@dstenger I was able to locally build the docker image.  Testing locally shows this test is passing.
